sonar.projectKey=timlaing_dovecot-xaps-daemon
sonar.organization=timlaing
sonar.projectName=dovecot-xaps-daemon

sonar.sources=cmd,internal
sonar.exclusions=**/*_test.go,internal/**/testdata/**
sonar.tests=internal
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
